[package]
name = "nomos-mempool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bincode = { version = "2.0.0-rc.2", features = ["serde"] }
futures = "0.3"
linked-hash-map = { version = "0.5.6", optional = true }
nomos-network = { path = "../network" }
nomos-da-network-core = { path = "../../nomos-da/network/core" }
nomos-da-sampling = { path = "../../nomos-services/data-availability/sampling/" }
nomos-core = { path = "../../nomos-core/chain-defs" }
full-replication = { path = "../../nomos-da/full-replication" }
kzgrs-backend = { path = "../../nomos-da/kzgrs-backend" }
overwatch-rs = { git = "https://github.com/logos-co/Overwatch", rev = "2f70806" }
rand = { version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"
tokio = { version = "1", features = ["sync", "macros"] }
tokio-stream = "0.1"
chrono = "0.4"
utoipa = { version = "4.0", optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
nomos-tracing-service = { path = "../tracing" }
overwatch-derive = { git = "https://github.com/logos-co/Overwatch", rev = "ac28d01" }
tokio = { version = "1", features = ["full"] }
blake2 = "0.10"

[features]
default = []
mock = ["linked-hash-map", "nomos-network/mock", "nomos-core/mock"]
libp2p = ["nomos-network/libp2p"]

# enable to help generate OpenAPI
openapi = ["dep:utoipa", "serde_json"]
