[package]
name = "nomos-network"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
bytes = "1.2"
chrono = { version = "0.4", optional = true }
humantime-serde = { version = "1", optional = true }
overwatch-rs = { git = "https://github.com/logos-co/Overwatch", rev = "2f70806" }
multiaddr = "0.15"
serde = { version = "1.0", features = ["derive"] }
sscanf = { version = "0.4", optional = true }
sled = { version = "0.34", optional = true }
tokio = { version = "1", features = ["sync"] }
tokio-stream = "0.1"
thiserror = "1.0"
tracing = "0.1"
rand = { version = "0.7.3", optional = true }
futures = "0.3"
parking_lot = "0.12"
nomos-core = { path = "../../nomos-core" }
nomos-libp2p = { path = "../../nomos-libp2p", optional = true }
nomos-metrics = { path = "../metrics", optional = true }
mixnet = { path = "../../mixnet", optional = true }

utoipa = { version = "4.0", optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = []
libp2p = ["nomos-libp2p", "rand", "humantime-serde"]
mixnet = ["dep:mixnet"]
mock = ["rand", "chrono"]
openapi = ["dep:utoipa", "serde_json"]
metrics = ["nomos-metrics"]
