[package]
name = "nomos-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
blake2 = "0.10"
bincode = "2.0.0-rc.2"
bytes = "1.3"
clap = { version = "4", features = ["derive", "env"] }
chrono = "0.4"
futures = "0.3"
http = "0.2.9"
hex = "0.4.3"
kzgrs-backend = { path = "../../nomos-da/kzgrs-backend" }
subnetworks-assignations = { path = "../../nomos-da/network/subnetworks-assignations" }
nomos-da-network-core = { path = "../../nomos-da/network/core" }
overwatch-rs = { git = "https://github.com/logos-co/Overwatch", rev = "2f70806" }
overwatch-derive = { git = "https://github.com/logos-co/Overwatch", rev = "ac28d01" }
tracing = "0.1"
multiaddr = "0.18"
nomos-core = { path = "../../nomos-core/chain-defs"}
nomos-da-sampling = { path = "../../nomos-services/data-availability/sampling", features = ["rocksdb-backend"] }
nomos-da-verifier = { path = "../../nomos-services/data-availability/verifier", features = ["rocksdb-backend", "libp2p"] }
nomos-da-indexer = { path = "../../nomos-services/data-availability/indexer", features = ["rocksdb-backend"] }
nomos-da-network-service = { path = "../../nomos-services/data-availability/network" }
nomos-network = { path = "../../nomos-services/network", features = ["libp2p"] }
nomos-mix-service = { path = "../../nomos-services/mix", features = ["libp2p"] }
nomos-api = { path = "../../nomos-services/api" }
nomos-tracing = { path = "../../nomos-tracing" }
nomos-tracing-service = { path = "../../nomos-services/tracing" }
nomos-mempool = { path = "../../nomos-services/mempool", features = [
    "mock",
    "libp2p",
] }
nomos-storage = { path = "../../nomos-services/storage", features = ["rocksdb"] }
cryptarchia-consensus = { path = "../../nomos-services/cryptarchia-consensus", features = ["libp2p"] }
nomos-libp2p = { path = "../../nomos-libp2p" }
nomos-system-sig = { path = "../../nomos-services/system-sig" }
tracing-subscriber = "0.3"
cryptarchia-engine = { path = "../../consensus/cryptarchia-engine" }
nomos-ledger = { path = "../../ledger/nomos-ledger" }
rand_chacha = "0.3"
cl = { path = "../../nomos-core/cl" }
tokio = { version = "1", features = ["sync"] }
serde_json = "1.0"
serde_yaml = "0.9"
color-eyre = "0.6.0"
serde = "1"
full-replication = { path = "../../nomos-da/full-replication" }
uuid = { version = "1.10", features = ["v4"] }
# openapi related dependencies
utoipa = "4.0"
utoipa-swagger-ui = { version = "4.0" }
# axum related dependencies
axum = { version = "0.6" }
hyper = { version = "0.14", features = ["full"] }
tower-http = { version = "0.4", features = ["cors", "trace"] }
time = "0.3"
rand = "0.8"

[features]
default = ["tracing"]
tracing = []
