[package]
name = "nomos-core"
version = "0.1.0"
edition = "2021"
authors = [
    "Daniel Sanchez Quiros <danielsq@status.im>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { version = "0.1" }
blake2 = { version = "0.10" }
bytes = "1.3"
carnot-engine = { path = "../../consensus/carnot-engine", features = ["serde"]}
cryptarchia-engine = { path = "../../consensus/cryptarchia-engine", features = ["serde"]}
nomos-ledger = { path = "../../ledger/nomos-ledger", features = ["serde"]}
nomos_risc0_proofs = { path = "../risc0_proofs" }
nomos_proof_statements = { path = "../proof_statements" }
cl =  { path = "../cl" }
futures = "0.3"
raptorq = { version = "1.7", optional = true }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
bincode = "1.3"
once_cell = "1.0"
indexmap = { version = "1.9", features = ["serde"] }
const-hex = "1"
risc0-zkvm = "1.1"
tracing = "0.1"
anyhow = "1.0"

[dev-dependencies]
rand = "0.8"
risc0-zkvm = { version = "1.1", features = ["prove"] }

[features]
default = []
raptor = ["raptorq"]
mock = []
