[package]
name = "nomos-mix-message"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sphinx-packet = "0.2"
thiserror = "1.0.65"
x25519-dalek = { version = "2.0.1", features = [
    "getrandom",
    "static_secrets",
    "serde",
] }

[dev-dependencies]
nomos-core = { path = "../../nomos-core/chain-defs" }
