[package]
name = "nomos-mix"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.53"
tokio = { version = "1", features = ["time", "sync", "macros"] }
tokio-stream = "0.1"
tracing = "0.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
nomos-mix-message = { path = "../message" }
futures = "0.3"
rand_chacha = "0.3"


[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
