[package]
name = "nomos-api"
version = "0.1.0"
edition = "2021"

[features]
default = ["axum"]
axum = ["dep:axum", "dep:hyper", "dep:tower-http", "utoipa-swagger-ui/axum"]

[dependencies]
async-trait = "0.1"
bytes = "1.2"
overwatch-rs = { git = "https://github.com/logos-co/Overwatch", rev = "2f70806" }
overwatch-derive = { git = "https://github.com/logos-co/Overwatch", rev = "ac28d01" }
tracing = "0.1"
nomos-core = { path = "../../nomos-core/chain-defs" }
cryptarchia-consensus = { path = "../cryptarchia-consensus" }
nomos-network = { path = "../../nomos-services/network" }
nomos-mix-service = { path = "../../nomos-services/mix", features = ["libp2p"] }
nomos-mempool = { path = "../../nomos-services/mempool", features = [
    "mock",
    "libp2p",
    "openapi",
] }
nomos-da-dispersal = { path = "../data-availability/dispersal" }
nomos-da-indexer = { path = "../data-availability/indexer", features = ["rocksdb-backend"] }
nomos-da-sampling = { path = "../data-availability/sampling" }
nomos-da-verifier = { path = "../data-availability/verifier", features = ["rocksdb-backend", "libp2p"] }
nomos-storage = { path = "../../nomos-services/storage", features = ["rocksdb"] }
nomos-libp2p = { path = "../../nomos-libp2p" }
full-replication = { path = "../../nomos-da/full-replication" }
kzgrs-backend = { path = "../../nomos-da/kzgrs-backend" }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
subnetworks-assignations = { path = "../../nomos-da/network/subnetworks-assignations" }
nomos-da-network-core = { path = "../../nomos-da/network/core" }
tokio = { version = "1", default-features = false, features = ["sync"] }


# axum related dependencies
axum = { version = "0.6", optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
tower-http = { version = "0.4", optional = true, features = ["cors", "trace"] }


# openapi related dependencies
utoipa = "4.0"
utoipa-swagger-ui = { version = "4.0" }

[dev-dependencies]
axum = "0.6"
hyper = { version = "0.14", features = ["full"] }
utoipa-swagger-ui = { version = "4.0", features = ["axum"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
